#!/bin/bash
#
#

while true; do
	./pyradium.py render -f -I examples/sub examples/example.xml -R rendered/foobar:foobar/ rendered -vvv
	inotifywait -q --exclude '\..*\.sw[a-z]' -e modify -e close_write -e create -r pyradium.py pyradium examples 
done
