#!/usr/bin/python3
#	pybeamer - HTML presentation/slide show generator
#	Copyright (C) 2015-2020 Johannes Bauer
#
#	This file is part of pybeamer.
#
#	pybeamer is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	pybeamer is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with pybeamer; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import sys
from FriendlyArgumentParser import FriendlyArgumentParser
from Presentation import Presentation
from Renderer import Renderer

parser = FriendlyArgumentParser(description = "Render a pybeamer template.")
parser.add_argument("-a", "--aspect", metavar = "x:y", default = "16:9", help = "Aspect ratio to use. Defaults to %(default)s.")
parser.add_argument("-m", "--mode", choices = [ "default", "handout" ], default = "default", help = "Mode in which the slides should be rendered. Can be either %(choices)s, defaults to %(default)s.")
parser.add_argument("--template-dir", metavar = "path", default = "default", help = "Source directory in which all templates are located. Defaults to the pybeamer/templates directory.")
parser.add_argument("-t", "--template", metavar = "name", default = "default", help = "Name of the template that should be rendered.")
parser.add_argument("-o", "--output", metavar = "path", default = "rendered", help = "Output directory in which the rendered template should be placed.")
parser.add_argument("-f", "--force", action = "store_true", help = "Overwrite the output directory even if it already exists.")
parser.add_argument("-v", "--verbose", action = "count", default = 0, help = "Increases verbosity. Can be specified multiple times to increase.")
parser.add_argument("presentation_xml", metavar = "presentation_xml", help = "Source file that should be rendered.")
args = parser.parse_args(sys.argv[1:])

presentation = Presentation(args.presentation_xml)
#presentation.dump()
renderer = Renderer()
rendered_master = renderer.render(presentation)
print(rendered_master)
