#!/bin/bash
#
#

which inotifywait >/dev/null 2>&1
if [ "$?" != "0" ]; then
	echo "inotify-tools not installed."
	exit 1
fi

if [ "$1" == "" ]; then
	echo "$0 [pyradium options]"
	exit 1
fi

while true; do
	./pyradium "$@"
	inotifywait -e close_write examples/*.xml templates/base/* templates/default/* *.py pyradium
done
